insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(1, 'Coca-Cola', 'COCA', 123.52, 100, 0, 0, 0, 1);
insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(2, 'Apple', 'AAPL', 145.52, 100, 0, 0, 0, 1);
insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(3, 'Google', 'GOO', 165.52, 100, 0, 0, 0, 1);
insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(4, 'Microsoft', 'MSFT', 223.52, 100, 0, 0, 0, 1);
insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(5, 'Dell', 'DEL', 125.52, 100, 0, 0, 0, 1);
insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(6, 'Penguin', 'PENG', 124.52, 100, 0, 0, 0, 1);
insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(7, 'Pepsi', 'PEP', 123.86, 100, 0, 0, 0, 1);
insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(8, 'Huawei', 'HWEI', 123.52, 100, 0, 0, 0, 1);
insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(9, 'Gold', 'GOLD', 123.52, 100, 0, 0, 0, 1);
insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(10, 'Samsung', 'SMNG', 123.52, 100, 0, 0, 0, 1);
insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(11, 'Amazon', 'AMZN', 123.52, 100, 0, 0, 0, 1);
insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(12, 'Epic Games', 'EPIC', 123.52, 100, 0, 0, 0, 1);
insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(13, 'EDF Energy', 'EDF', 123.52, 100, 0, 0, 0, 1);
insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(14, 'Toyota', 'TYTA', 123.52, 100, 0, 0, 0, 1);
insert stocks (stock_id, company, ticker, share_price, volume, opening_value, closing_value, profit_loss, fk_account) values(15, 'Exxon Mobile', 'EXX', 123.52, 100, 0, 0, 0, 1);